# Build settings
gems:
  - jemoji
  - jekyll-paginate

# Site settings
title: "James Carleton"
description: > # this means to ignore newlines until "email:"
   UX Designer

email: me@carletondesign.com
#blog logo
logo: "/assets/images/df_logo.jpg"
# blog cover
cover: "/assets/images/shattered-island.gif"

name: 'Dirk Fabisch'
author: 'Dirk Fabisch'
author_image: "/assets/images/author.jpg"

paginate:	5

url: "http://carletondesign.com" # the base hostname & protocol for your site
baseurl: ""
#used to display twitter cards
twitter_handle: '@jamescarleton'

#fill in disqus shortname to use disqus
#disqus: disqus-shortname

# social icons and sharing options
social:
  - icon:	twitter
    url:	https://twitter.com/jamescarleton
    desc: Follow me on twitter
    share_url: http://twitter.com/share
    share_title: ?text=
    share_link: "&amp;url="

#  - icon:	facebook
#    url:	https://facebook.com/???
#    desc: Connect with me facebook
#    share_url: https://www.facebook.com/sharer.php
#    share_title: ?t=
#    share_link: "&amp;u="

  - icon:	github
    url:	https://github.com/fwg001
    desc:	Follow me on github
    share_url:
    share_title:
    share_link:

#  - icon:	google-plus
#    url:	https://google.com/???
#    desc:	Add me on google+
#    share_url:
#    share_title:
#    share_link:

port: 3000 # change server port to 3000
